import type { ReportPreview, ReportSummaryItem } from '../../types/report';
import { formatCurrency } from '../money';
import { sanitizeCell } from '../csv';

export interface ExportPdfParams {
  previewData: ReportPreview;
  subsidiary: string;
  dateStart: string;
  dateEnd: string;
  generatedBy: string;
  fileName: string;
  chartElement: HTMLDivElement | null;
  onChartRenderStart?: () => void;
  onChartRenderEnd?: () => void;
}

export async function exportReportPdf(params: ExportPdfParams): Promise<void> {
  const {
    previewData, subsidiary, dateStart, dateEnd, generatedBy, fileName,
    chartElement, onChartRenderStart, onChartRenderEnd,
  } = params;

  if (!previewData.data.length) return;

  const [{ default: jsPDF }, { default: autoTable }, { default: html2canvas }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
    import('html2canvas'),
  ]);

  // previewData.data's shape differs per report type (bar/line: {name,value}; composed:
  // {name,estimated,actual}) — the PDF/Excel table is genuinely generic over whichever
  // columns a given report produces, so row access is intentionally untyped here.
  const rows = previewData.data as unknown as Record<string, unknown>[];
  const headers = Object.keys(rows[0]);
  const numericHeaders = headers.filter(h => typeof rows[0][h] === 'number');

  const formatCell = (header: string, value: unknown): string | number => {
    const sanitized = sanitizeCell(value);
    return numericHeaders.includes(header) && typeof sanitized === 'number'
      ? formatCurrency(sanitized)
      : (sanitized as string | number);
  };

  const totalsRow = headers.map((header, idx) => {
    if (idx === 0) return 'Total';
    if (!numericHeaders.includes(header)) return '';
    const sum = rows.reduce((s, row) => s + (Number(row[header]) || 0), 0);
    return formatCurrency(sum);
  });

  const doc = new jsPDF();
  doc.setFontSize(14);
  doc.text(previewData.title, 14, 16);
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`${subsidiary} | ${dateStart} - ${dateEnd}`, 14, 23);
  doc.text(`Generated by ${generatedBy} on ${new Date().toLocaleString()}`, 14, 28);

  const summary: ReportSummaryItem[] = previewData.summary ?? [];
  let cursorY = 34;
  if (summary.length) {
    const boxWidth = 45;
    const boxGap = 3;
    const summaryY = 40;
    summary.forEach((item, idx) => {
      const x = 14 + idx * (boxWidth + boxGap);
      doc.setFontSize(7.5);
      doc.setTextColor(120);
      doc.text(item.label, x, summaryY);
      doc.setFontSize(11);
      doc.setTextColor(30);
      doc.text(item.value, x, summaryY + 6);
    });
    cursorY = 54;
  }

  onChartRenderStart?.();
  try {
    if (chartElement) {
      const canvas = await html2canvas(chartElement, { backgroundColor: '#ffffff', scale: 2 });
      const imgWidth = 180;
      const imgHeight = (canvas.height / canvas.width) * imgWidth;
      doc.addImage(canvas.toDataURL('image/png'), 'PNG', 14, cursorY, imgWidth, imgHeight);
      cursorY += imgHeight + 10;
    }
  } finally {
    onChartRenderEnd?.();
  }

  autoTable(doc, {
    startY: cursorY,
    head: [headers],
    body: rows.map(row => headers.map(h => formatCell(h, row[h]))),
    foot: [totalsRow],
    footStyles: { fontStyle: 'bold', fillColor: [241, 245, 249] },
  });

  const detailColumns = previewData.detailColumns as { key: string; label: string; currency?: boolean }[];
  const detailData = previewData.detailData as unknown as Record<string, unknown>[];
  if (detailColumns.length && detailData.length) {
    doc.addPage();
    doc.setFontSize(12);
    doc.setTextColor(30);
    doc.text('Detail Records', 14, 16);
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(`${detailData.length} record(s)`, 14, 22);

    const varianceColIndex = detailColumns.findIndex(c => c.key === 'variance');

    autoTable(doc, {
      startY: 28,
      head: [detailColumns.map(c => c.label)],
      body: detailData.map(row =>
        detailColumns.map(c => {
          const value = row[c.key];
          return c.currency && typeof value === 'number' ? formatCurrency(value) : String(value ?? '');
        })
      ),
      styles: { fontSize: 8 },
      didParseCell: (data) => {
        if (varianceColIndex === -1 || data.section !== 'body' || data.column.index !== varianceColIndex) return;
        const variance = detailData[data.row.index]?.variance;
        if (typeof variance === 'number' && variance > 0) {
          data.cell.styles.textColor = [220, 38, 38];
          data.cell.styles.fontStyle = 'bold';
        }
      },
    });
  }

  const pageHeight = doc.internal.pageSize.getHeight();
  const pageWidth = doc.internal.pageSize.getWidth();
  const approvalBlockHeight = 40;
  // jspdf-autotable attaches `lastAutoTable` to the doc instance but doesn't extend jsPDF's
  // own type declarations, so this one cast is unavoidable.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let approvalY = ((doc as any).lastAutoTable?.finalY ?? cursorY) + 20;
  if (approvalY + approvalBlockHeight > pageHeight - 15) {
    doc.addPage();
    approvalY = 20;
  }

  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text('Sign-off', 14, approvalY - 8);

  const marginX = 14;
  const colWidth = (pageWidth - marginX * 2) / 3;
  (['Prepared by', 'Reviewed by', 'Approved by'] as const).forEach((label, idx) => {
    const x = marginX + idx * colWidth;
    doc.setFontSize(9);
    doc.setTextColor(30);
    doc.setFont('helvetica', 'bold');
    doc.text(label, x, approvalY);
    doc.setFont('helvetica', 'normal');

    doc.setDrawColor(150);
    doc.line(x, approvalY + 14, x + colWidth - 12, approvalY + 14);

    doc.setFontSize(8);
    doc.setTextColor(100);
    doc.text('Name: _______________________', x, approvalY + 20);
    doc.text('Date: _______________________', x, approvalY + 26);
  });

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() - 30,
      doc.internal.pageSize.getHeight() - 10
    );
  }

  doc.save(`${fileName}.pdf`);
}
